{
  "swagger": "2.0",
  "info": {
    "title": "external/iam/v2/teams.proto",
    "version": "version not set"
  },
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/apis/iam/v2/teams": {
      "get": {
        "summary": "Lists all local teams",
        "description": "Lists all local teams.\n\nAuthorization Action:\n```\niam:teams:list\n```",
        "operationId": "Teams_ListTeams",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/chef.automate.api.iam.v2.ListTeamsResp"
            }
          },
          "default": {
            "description": "An unexpected error response",
            "schema": {
              "$ref": "#/definitions/grpc.gateway.runtime.Error"
            }
          }
        },
        "tags": [
          "teams"
        ]
      },
      "post": {
        "summary": "Creates a local team",
        "description": "Creates a local team that is used to group local users as members of IAM policies.\n\nAuthorization Action:\n```\niam:teams:create\n```",
        "operationId": "Teams_CreateTeam",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/chef.automate.api.iam.v2.CreateTeamResp"
            }
          },
          "default": {
            "description": "An unexpected error response",
            "schema": {
              "$ref": "#/definitions/grpc.gateway.runtime.Error"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/chef.automate.api.iam.v2.CreateTeamReq"
            }
          }
        ],
        "tags": [
          "teams"
        ],
        "x-code-samples": [
          {
            "lang": "JSON",
            "source": "{\"id\": \"test-id\", \"name\": \"My Test Team\", \"projects\": [\"project1\", \"project2\"]}"
          }
        ]
      }
    },
    "/apis/iam/v2/teams/{id}": {
      "get": {
        "summary": "Get a team",
        "description": "Returns the details for a team.\n\nAuthorization Action:\n```\niam:teams:get\n```",
        "operationId": "Teams_GetTeam",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/chef.automate.api.iam.v2.GetTeamResp"
            }
          },
          "default": {
            "description": "An unexpected error response",
            "schema": {
              "$ref": "#/definitions/grpc.gateway.runtime.Error"
            }
          }
        },
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "tags": [
          "teams"
        ]
      },
      "delete": {
        "summary": "Deletes a local team",
        "description": "Deletes a local team and removes it from any policies.\n\nAuthorization Action:\n```\niam:teams:delete\n```",
        "operationId": "Teams_DeleteTeam",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/chef.automate.api.iam.v2.DeleteTeamResp"
            }
          },
          "default": {
            "description": "An unexpected error response",
            "schema": {
              "$ref": "#/definitions/grpc.gateway.runtime.Error"
            }
          }
        },
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "tags": [
          "teams"
        ]
      },
      "put": {
        "summary": "Updates a local team",
        "description": "Updates a local team.\n\nAuthorization Action:\n```\niam:teams:update\n```",
        "operationId": "Teams_UpdateTeam",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/chef.automate.api.iam.v2.UpdateTeamResp"
            }
          },
          "default": {
            "description": "An unexpected error response",
            "schema": {
              "$ref": "#/definitions/grpc.gateway.runtime.Error"
            }
          }
        },
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/chef.automate.api.iam.v2.UpdateTeamReq"
            }
          }
        ],
        "tags": [
          "teams"
        ],
        "x-code-samples": [
          {
            "lang": "JSON",
            "source": "{\"name\": \"My Update Test Team\", \"projects\": [\"project1\", \"projectnew\"]}"
          }
        ]
      }
    },
    "/apis/iam/v2/teams/{id}/users": {
      "get": {
        "summary": "Gets local team membership",
        "description": "Lists all users of a local team. Users are listed by their membership_id.\n\nAuthorization Action:\n```\niam:teamUsers:list\n```",
        "operationId": "Teams_GetTeamMembership",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/chef.automate.api.iam.v2.GetTeamMembershipResp"
            }
          },
          "default": {
            "description": "An unexpected error response",
            "schema": {
              "$ref": "#/definitions/grpc.gateway.runtime.Error"
            }
          }
        },
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "tags": [
          "teams"
        ]
      }
    },
    "/apis/iam/v2/teams/{id}/users:add": {
      "post": {
        "summary": "Adds local team membership",
        "description": "Adds a list of users to a local team. Users are added by their membership_id.\nThe request currently does not validate that membership_id maps to a real user.\n\nThe membership_id for users can be found via GET /apis/apis/iam/v2/users/\u003cuser_id\u003e.\n\nAuthorization Action:\n```\niam:teamUsers:create\n```",
        "operationId": "Teams_AddTeamMembers",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/chef.automate.api.iam.v2.AddTeamMembersResp"
            }
          },
          "default": {
            "description": "An unexpected error response",
            "schema": {
              "$ref": "#/definitions/grpc.gateway.runtime.Error"
            }
          }
        },
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/chef.automate.api.iam.v2.AddTeamMembersReq"
            }
          }
        ],
        "tags": [
          "teams"
        ],
        "x-code-samples": [
          {
            "lang": "JSON",
            "source": "{membership_ids: [\"527ed96f-2ecb-4f8f-abd7-0bf6511459ac\", \"987c8475-5747-4f9b-a766-c337f73965ae\"]}"
          }
        ]
      }
    },
    "/apis/iam/v2/teams/{id}/users:remove": {
      "post": {
        "summary": "Removes local team membership",
        "description": "Removes a list of users from a local team. Users are removed by their membership_id.\nThe request currently does not validate that membership_id maps to a real user.\n\nThe membership_id for users can be found via GET /apis/apis/iam/v2/users/\u003cuser_id\u003e.\n\nAuthorization Action:\n```\niam:teamUsers:delete\n```",
        "operationId": "Teams_RemoveTeamMembers",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/chef.automate.api.iam.v2.RemoveTeamMembersResp"
            }
          },
          "default": {
            "description": "An unexpected error response",
            "schema": {
              "$ref": "#/definitions/grpc.gateway.runtime.Error"
            }
          }
        },
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/chef.automate.api.iam.v2.RemoveTeamMembersReq"
            }
          }
        ],
        "tags": [
          "teams"
        ],
        "x-code-samples": [
          {
            "lang": "JSON",
            "source": "{membership_ids: [\"527ed96f-2ecb-4f8f-abd7-0bf6511459ac\", \"987c8475-5747-4f9b-a766-c337f73965ae\"]}"
          }
        ]
      }
    },
    "/apis/iam/v2/users/{membership_id}/teams": {
      "get": {
        "summary": "Gets team membership for a user",
        "description": "Lists all local teams for a specific user. You must use their membership_id in the request URL.\n\nAuthorization Action:\n```\niam:userTeams:get\n```",
        "operationId": "Teams_GetTeamsForMember",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/chef.automate.api.iam.v2.GetTeamsForMemberResp"
            }
          },
          "default": {
            "description": "An unexpected error response",
            "schema": {
              "$ref": "#/definitions/grpc.gateway.runtime.Error"
            }
          }
        },
        "parameters": [
          {
            "name": "membership_id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "tags": [
          "teams"
        ]
      }
    }
  },
  "definitions": {
    "chef.automate.api.iam.v2.AddTeamMembersReq": {
      "type": "object",
      "example": {
        "id": "admins",
        "membership_ids": [
          "527ed96f-2ecb-4f8f-abd7-0bf6511459ac",
          "353a62d4-85fa-4423-b12a-f6608a562ae9"
        ]
      },
      "properties": {
        "id": {
          "type": "string"
        },
        "membership_ids": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "id",
        "membership_ids"
      ]
    },
    "chef.automate.api.iam.v2.AddTeamMembersResp": {
      "type": "object",
      "example": {
        "membership_ids": [
          "527ed96f-2ecb-4f8f-abd7-0bf6511459ac",
          "353a62d4-85fa-4423-b12a-f6608a562ae9"
        ]
      },
      "properties": {
        "membership_ids": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "chef.automate.api.iam.v2.CreateTeamReq": {
      "type": "object",
      "example": {
        "id": "my-team-id",
        "name": "My Test Team",
        "projects": [
          "project1",
          "project2"
        ]
      },
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "projects": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "id",
        "name"
      ]
    },
    "chef.automate.api.iam.v2.CreateTeamResp": {
      "type": "object",
      "example": {
        "team": {
          "id": "test-id",
          "name": "My Test Team",
          "projects": [
            "project1",
            "project2"
          ]
        }
      },
      "properties": {
        "team": {
          "$ref": "#/definitions/chef.automate.api.iam.v2.Team"
        }
      }
    },
    "chef.automate.api.iam.v2.DeleteTeamResp": {
      "type": "object",
      "example": {
        "team": {
          "id": "test-id",
          "name": "My Test Team",
          "projects": [
            "project1",
            "project2"
          ]
        }
      },
      "properties": {
        "team": {
          "$ref": "#/definitions/chef.automate.api.iam.v2.Team"
        }
      }
    },
    "chef.automate.api.iam.v2.GetTeamMembershipResp": {
      "type": "object",
      "example": {
        "membership_ids": [
          "527ed96f-2ecb-4f8f-abd7-0bf6511459ac",
          "353a62d4-85fa-4423-b12a-f6608a562ae9"
        ]
      },
      "properties": {
        "membership_ids": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "chef.automate.api.iam.v2.GetTeamResp": {
      "type": "object",
      "example": {
        "team": {
          "id": "test-id",
          "name": "My Test Team",
          "projects": [
            "project1",
            "project2"
          ]
        }
      },
      "properties": {
        "team": {
          "$ref": "#/definitions/chef.automate.api.iam.v2.Team"
        }
      }
    },
    "chef.automate.api.iam.v2.GetTeamsForMemberResp": {
      "type": "object",
      "example": {
        "teams": [
          {
            "id": "test-1",
            "name": "My Test Team",
            "projects": [
              "project1",
              "project2"
            ]
          },
          {
            "id": "test-2",
            "name": "My Test Team 2",
            "projects": [
              "project1"
            ]
          }
        ]
      },
      "properties": {
        "teams": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/chef.automate.api.iam.v2.Team"
          }
        }
      }
    },
    "chef.automate.api.iam.v2.ListTeamsResp": {
      "type": "object",
      "example": {
        "teams": [
          {
            "id": "test-1",
            "name": "My Test Team",
            "projects": [
              "project1",
              "project2"
            ]
          },
          {
            "id": "test-2",
            "name": "My Test Team 2",
            "projects": [
              "project1"
            ]
          }
        ]
      },
      "properties": {
        "teams": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/chef.automate.api.iam.v2.Team"
          }
        }
      }
    },
    "chef.automate.api.iam.v2.RemoveTeamMembersReq": {
      "type": "object",
      "example": {
        "id": "admins",
        "membership_ids": [
          "527ed96f-2ecb-4f8f-abd7-0bf6511459ac",
          "353a62d4-85fa-4423-b12a-f6608a562ae9"
        ]
      },
      "properties": {
        "id": {
          "type": "string"
        },
        "membership_ids": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "id",
        "membership_ids"
      ]
    },
    "chef.automate.api.iam.v2.RemoveTeamMembersResp": {
      "type": "object",
      "example": {
        "membership_ids": [
          "527ed96f-2ecb-4f8f-abd7-0bf6511459ac",
          "353a62d4-85fa-4423-b12a-f6608a562ae9"
        ]
      },
      "properties": {
        "membership_ids": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "chef.automate.api.iam.v2.Team": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "projects": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "chef.automate.api.iam.v2.UpdateTeamReq": {
      "type": "object",
      "example": {
        "id": "my-team-id",
        "name": "My Test Team",
        "projects": [
          "project1",
          "project2"
        ]
      },
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "projects": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "id",
        "name"
      ]
    },
    "chef.automate.api.iam.v2.UpdateTeamResp": {
      "type": "object",
      "example": {
        "team": {
          "id": "test-id",
          "name": "My Test Team",
          "projects": [
            "project1",
            "project2"
          ]
        }
      },
      "properties": {
        "team": {
          "$ref": "#/definitions/chef.automate.api.iam.v2.Team"
        }
      }
    },
    "google.protobuf.Any": {
      "type": "object",
      "properties": {
        "type_url": {
          "type": "string",
          "description": "A URL/resource name that uniquely identifies the type of the serialized\nprotocol buffer message. This string must contain at least\none \"/\" character. The last segment of the URL's path must represent\nthe fully qualified name of the type (as in\n`path/google.protobuf.Duration`). The name should be in a canonical form\n(e.g., leading \".\" is not accepted).\n\nIn practice, teams usually precompile into the binary all types that they\nexpect it to use in the context of Any. However, for URLs which use the\nscheme `http`, `https`, or no scheme, one can optionally set up a type\nserver that maps type URLs to message definitions as follows:\n\n* If no scheme is provided, `https` is assumed.\n* An HTTP GET on the URL must yield a [google.protobuf.Type][]\n  value in binary format, or produce an error.\n* Applications are allowed to cache lookup results based on the\n  URL, or have them precompiled into a binary to avoid any\n  lookup. Therefore, binary compatibility needs to be preserved\n  on changes to types. (Use versioned type names to manage\n  breaking changes.)\n\nNote: this functionality is not currently available in the official\nprotobuf release, and it is not used for type URLs beginning with\ntype.googleapis.com.\n\nSchemes other than `http`, `https` (or the empty scheme) might be\nused with implementation specific semantics."
        },
        "value": {
          "type": "string",
          "format": "byte",
          "description": "Must be a valid serialized protocol buffer of the above specified type."
        }
      },
      "description": "`Any` contains an arbitrary serialized protocol buffer message along with a\nURL that describes the type of the serialized message.\n\nProtobuf library provides support to pack/unpack Any values in the form\nof utility functions or additional generated methods of the Any type.\n\nExample 1: Pack and unpack a message in C++.\n\n    Foo foo = ...;\n    Any any;\n    any.PackFrom(foo);\n    ...\n    if (any.UnpackTo(\u0026foo)) {\n      ...\n    }\n\nExample 2: Pack and unpack a message in Java.\n\n    Foo foo = ...;\n    Any any = Any.pack(foo);\n    ...\n    if (any.is(Foo.class)) {\n      foo = any.unpack(Foo.class);\n    }\n\n Example 3: Pack and unpack a message in Python.\n\n    foo = Foo(...)\n    any = Any()\n    any.Pack(foo)\n    ...\n    if any.Is(Foo.DESCRIPTOR):\n      any.Unpack(foo)\n      ...\n\n Example 4: Pack and unpack a message in Go\n\n     foo := \u0026pb.Foo{...}\n     any, err := anypb.New(foo)\n     if err != nil {\n       ...\n     }\n     ...\n     foo := \u0026pb.Foo{}\n     if err := any.UnmarshalTo(foo); err != nil {\n       ...\n     }\n\nThe pack methods provided by protobuf library will by default use\n'type.googleapis.com/full.type.name' as the type URL and the unpack\nmethods only use the fully qualified type name after the last '/'\nin the type URL, for example \"foo.bar.com/x/y.z\" will yield type\nname \"y.z\".\n\n\nJSON\n====\nThe JSON representation of an `Any` value uses the regular\nrepresentation of the deserialized, embedded message, with an\nadditional field `@type` which contains the type URL. Example:\n\n    package google.profile;\n    message Person {\n      string first_name = 1;\n      string last_name = 2;\n    }\n\n    {\n      \"@type\": \"type.googleapis.com/google.profile.Person\",\n      \"firstName\": \u003cstring\u003e,\n      \"lastName\": \u003cstring\u003e\n    }\n\nIf the embedded message type is well-known and has a custom JSON\nrepresentation, that representation will be embedded adding a field\n`value` which holds the custom JSON in addition to the `@type`\nfield. Example (for message [google.protobuf.Duration][]):\n\n    {\n      \"@type\": \"type.googleapis.com/google.protobuf.Duration\",\n      \"value\": \"1.212s\"\n    }"
    },
    "grpc.gateway.runtime.Error": {
      "type": "object",
      "properties": {
        "error": {
          "type": "string"
        },
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        },
        "details": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/google.protobuf.Any"
          }
        }
      }
    }
  }
}
